### ISSUE TITLE
ticks on colorbar are not rendering properly when ordinal color scale is used

### ISSUE THREAD

**Issue by ChakriCherukuri** [bloomberg/bqplot#765]
Code snippet to reproduce the issue:

```python
from bqplot import *
import numpy as np

n = 5
size_data = np.random.rand(n)
color_data = np.arange(n)

cs = OrdinalColorScale(scheme='Reds')
cax = ColorAxis(scale=cs)

pie = Pie(sizes=size_data, scales={'color': cs}, color=color_data)
Figure(marks=[pie], axes=[cax])
```
In the console I see the following error:<br>
d3.js:670 Error: <g> attribute transform: Expected number, "translate(NaN,0)"

![image](https://user-images.githubusercontent.com/5638994/50179816-03b59700-02d6-11e9-926d-137e8eaa63b9.png)

**Comment by ChakriCherukuri** [comment]
@rmenegaux Is this related to changes to ColorAxis you'd made in Feb? Can you please take a look?

**Comment by SylvainCorlay** [comment]
I did some git bisect and this broke with PR #605 indeed.

**Comment by SylvainCorlay** [comment]
@ChakriCherukuri this is fixed in master and 0.11.x.
